name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive project
        run: |
          tar --exclude='.git' --exclude='node_modules' --ignore-failed-read -czf deploy.tar.gz .

      - name: Upload file via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          source: "deploy.tar.gz"
          target: "/root/bot"

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/bot
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            bun install --no-save
            systemctl restart bot
